### ISSUE TITLE
Add ESLint

### ISSUE THREAD

**Issue by ppseprus** [csabbee/online-bookmark#11]
It would be nice to have ESLint as well.
Editorconfig generalises basic thing, but we should have code conventions for the code style as well.

**Comment by csabbee** [comment]
Good thinking. But I am afraid that jsx syntax could throw the linter off

**Comment by ppseprus** [comment]
"The pluggable linting utility for JavaScript and JSX"
This is written on their website! : )

**Comment by ppseprus** [comment]
PR #12 is merged.
