### ISSUE TITLE
Backend technology

### ISSUE THREAD

**Issue by csabbee** [csabbee/online-bookmark#5]
What technology should be used to create the backend?
- nodejs + express
- spring mvc
- ruby on rails (edit)

others can be added as comment

**Comment by kicsikrumpli** [comment]
Ruby on Rails?

**Comment by ppseprus** [comment]
After a very short Googling, my vote is on nodejs + express... : )

**Comment by csabbee** [comment]
The winner is: nodejs + express + swagger
